@testable import FeedbackSwift
import XCTest

final class FeedbackGeneratorTests: XCTestCase {
    func testPlainTextGeneration() {
        let config = makeConfiguration(toRecipients: ["to@test.com"])
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: "user@test.com",
            topic: Topic.bugReport,
            body: "Something broke",
            media: nil,
            deviceName: "iPhone15,2",
            systemVersion: "17.0",
            appName: "TestApp",
            appVersion: "1.0",
            appBuild: "42"
        )

        XCTAssertEqual(feedback.email, "user@test.com")
        XCTAssertEqual(feedback.to, ["to@test.com"])
        XCTAssertFalse(feedback.isHTML)
        XCTAssertTrue(feedback.body.contains("Something broke"))
        XCTAssertTrue(feedback.body.contains("iPhone15,2"))
        XCTAssertTrue(feedback.body.contains("17.0"))
        XCTAssertTrue(feedback.body.contains("TestApp"))
        XCTAssertTrue(feedback.body.contains("1.0"))
        XCTAssertTrue(feedback.body.contains("42"))
        XCTAssertNil(feedback.jpeg)
        XCTAssertNil(feedback.mp4)
    }

    func testHTMLGeneration() {
        let config = makeConfiguration(usesHTML: true)
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: Topic.question,
            body: "Line1\nLine2",
            media: nil,
            deviceName: "Mac",
            systemVersion: "14.0",
            appName: "App",
            appVersion: "2.0",
            appBuild: "100"
        )

        XCTAssertTrue(feedback.isHTML)
        XCTAssertTrue(feedback.body.contains("<br />"))
        XCTAssertTrue(feedback.body.contains("<b>Mac</b>"))
        XCTAssertTrue(feedback.body.contains("<b>14.0</b>"))
        XCTAssertTrue(feedback.body.contains("<b>App</b>"))
        XCTAssertTrue(feedback.body.contains("<b>2.0</b>"))
        XCTAssertTrue(feedback.body.contains("<b>100</b>"))
        XCTAssertNil(feedback.email)
    }

    func testAutoGeneratedSubject() {
        let config = makeConfiguration(subject: nil)
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: Topic.bugReport,
            body: "",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "MyApp",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertTrue(feedback.subject.contains("MyApp"))
        XCTAssertTrue(feedback.subject.contains(Topic.bugReport.localizedTitle))
    }

    func testCustomSubjectOverridesAutoGenerated() {
        let config = makeConfiguration(subject: "Custom Subject")
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: Topic.bugReport,
            body: "",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "MyApp",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertEqual(feedback.subject, "Custom Subject")
    }

    func testRecipientsPropagated() {
        let config = makeConfiguration(
            toRecipients: ["a@b.com"],
            ccRecipients: ["cc@b.com"],
            bccRecipients: ["bcc@b.com"]
        )
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: nil,
            body: "",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertEqual(feedback.to, ["a@b.com"])
        XCTAssertEqual(feedback.cc, ["cc@b.com"])
        XCTAssertEqual(feedback.bcc, ["bcc@b.com"])
    }

    func testAdditionalDiagnosticContentAppended() {
        let config = makeConfiguration(additionalDiagnosticContent: "\nDiag: extra")
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: nil,
            body: "Body",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertTrue(feedback.body.contains("Diag: extra"))
    }

    func testAdditionalDiagnosticContentInHTML() {
        let config = makeConfiguration(
            additionalDiagnosticContent: "<p>Extra</p>",
            usesHTML: true
        )
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: nil,
            body: "Body",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertTrue(feedback.body.contains("<p>Extra</p>"))
    }

    func testImageAttachmentProducesJpeg() {
        let img = makeTestImage()
        let config = makeConfiguration()
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: nil,
            body: "",
            media: .image(img),
            deviceName: "",
            systemVersion: "",
            appName: "",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertNotNil(feedback.jpeg)
        XCTAssertNil(feedback.mp4)
    }

    func testNilTopicSubject() {
        let config = makeConfiguration(subject: nil)
        let feedback = FeedbackGenerator.generate(
            configuration: config,
            email: nil,
            topic: nil,
            body: "",
            media: nil,
            deviceName: "",
            systemVersion: "",
            appName: "App",
            appVersion: "",
            appBuild: ""
        )

        XCTAssertEqual(feedback.subject, "App: ")
    }
}
