name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-12
    steps:
      - uses: swift-actions/setup-swift@v1.19.0
        with:
          swift-version: "5.7.0"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-FeedbackSwift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-FeedbackSwift
      - name: Build
        run: xcodebuild build -scheme FeedbackSwift -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
