name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-15
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-FeedbackSwift-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-FeedbackSwift
      - name: Build
        run: xcodebuild build -scheme FeedbackSwift -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16"
